# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba25aea4cfd6e08f837e9567f302cf64b64fe88ac546d53ffbcf9f82e618351174802ec9d1c76a714b7ce6e7ec120990fbd8aaea0987dbc1d12d0d5d2c5ee214
  google_api_key: 676483520639-gv7qmp654unfeup8u3dr064fpoqo129u.apps.googleusercontent.com
  google_api_secret: k--noay71GvuiSL4Pycl3mwP

test:
  secret_key_base: 0531ce72227ac462998a70e7126f00e7a73b26e1a257bbb26529eb74d328dffb3d4e44c331edcff2f527e9525b21d8ec900923950f1818dd5dd20b2c6babec8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a6b26c30603a83b1585447d4f7388be3026e6cbc111583283b1c62744c457c057369c7f447c7dece93568afd9a0c92d54962c459a09a7e51ea1b13dd22d1c9b5
  google_api_key: 676483520639-gv7qmp654unfeup8u3dr064fpoqo129u.apps.googleusercontent.com
  google_api_secret: k--noay71GvuiSL4Pycl3mwP
